var studentData = {
  studentData: [
    {
      id: 1,
      category: "Business",
      major: "Marketing",
      year: "First Year",
      college: "University of Denver",
      payment: "Paid",
      hours: "0-10",
      length: "2 Quarters",
      summer: "Yes",
      contactName: "Malcom X",
      contactEmail: "malcom@heythere.com",
      contactPhone: "123-456-7890",
      preferredContactMethod: "phone",
      extraLinks: "www.malcomisthebest.com"
    },
    {
      id: 2,
      category: "Business",
      major: "Finance",
      year: "Second Year",
      college: "University of Colorado at Denver",
      payment: "For Credit",
      hours: "10-15",
      length: "1 Semester",
      summer: "No ",
      contactName: "Rosa parks",
      contactEmail: "rosa@backdafup.com",
      contactPhone: "555-444-9999",
      preferredContactMethod: "email",
      extraLinks: "www.resist.com"
    },
    {
      id: 3,
      category: "Business",
      major: "Accounting",
      year: "Third Year",
      college: "Metropolitan State University ",
      payment: "Either",
      hours: "15-20",
      length: "2 Semesters",
      summer: "Not Sure",
      contactName: "James Baldwin",
      contactEmail: "jamescantbetamed@me.com",
      contactPhone: "234-654-8892",
      preferredContactMethod: "either",
      "extra links": "hello.com"
    },
    {
      id: 4,
      category: "Business ",
      major: "Management",
      year: "Forth Year",
      college: "Colorado State University",
      payment: "Paid",
      hours: "25+",
      length: "Summer",
      summer: "Yes",
      contactName: "Sarah Johnson",
      contactEmail: "sarah@hi.com",
      contactPhone: "887-398-0090",
      preferredContactMethod: "phone",
      extraLinks: "heyhow.com"
    },
    {
      id: 5,
      category: "Healthcare",
      major: "Physician's Assistant",
      year: "Masters",
      college: "Colorado State University",
      payment: "Paid",
      hours: "25+",
      length: "Summer",
      summer: "Yes",
      contactName: "Sean Storey",
      contactEmail: "sean@hi.com",
      contactPhone: "887-398-0090",
      preferredContactMethod: "phone",
      extraLinks: "pasrock.com"
    },
    {
      id: 6,
      category: "Sciences ",
      major: "Engineering",
      year: "Masters",
      college: "Colorado State University",
      payment: "Paid",
      hours: "25+",
      length: "Summer",
      summer: "Yes",
      contactName: "Audre Lord",
      contactEmail: "audre@hi.com",
      contactPhone: "887-365-0090",
      preferredContactMethod: "phone",
      extraLinks: "heyhowareya.com"
    }
  ]
};

module.exports = { studentData };
